export const dynamic = "force-dynamic";

import Link from "next/link";
import { Calendar, Sparkles, AlertTriangle, Clock, CheckCircle2, User } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { listInspections, type Inspection, type InspectionStatus } from "@/lib/supabase/inspection-service";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];

function chipVariant(status: InspectionStatus, isOverdue: boolean): string {
  if (isOverdue) return "calendar-chip--overdue";
  if (status === "in_progress") return "calendar-chip--in-progress";
  if (status === "completed") return "calendar-chip--completed";
  if (status === "cancelled") return "calendar-chip--cancelled";
  return ""; // planned = default blue
}

function statusIcon(status: InspectionStatus) {
  if (status === "planned")     return <Clock size={11} />;
  if (status === "in_progress") return <AlertTriangle size={11} />;
  if (status === "completed")   return <CheckCircle2 size={11} />;
  return null;
}

function groupByMonth(inspections: Inspection[]): Map<string, Inspection[]> {
  const map = new Map<string, Inspection[]>();
  for (const insp of inspections) {
    const dateStr = insp.nextDueDate ?? insp.scheduledFor ?? insp.createdAt;
    if (!dateStr) continue;
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) continue;
    const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
    if (!map.has(key)) map.set(key, []);
    map.get(key)!.push(insp);
  }
  for (const [, items] of map) {
    items.sort((a, b) => {
      const da = new Date(a.nextDueDate ?? a.scheduledFor ?? "");
      const db = new Date(b.nextDueDate ?? b.scheduledFor ?? "");
      return da.getTime() - db.getTime();
    });
  }
  return map;
}

function buildMonthRange(): string[] {
  const now = new Date();
  const keys: string[] = [];
  for (let i = -1; i <= 11; i++) {
    const d = new Date(now.getFullYear(), now.getMonth() + i, 1);
    keys.push(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`);
  }
  return keys;
}

// ---------------------------------------------------------------------------
// Components
// ---------------------------------------------------------------------------

function InspectionChip({ insp }: { insp: Inspection }) {
  const dateStr = insp.nextDueDate ?? insp.scheduledFor;
  const day = dateStr ? new Date(dateStr).getDate() : null;
  const isOverdue = insp.status === "planned" && !!dateStr && new Date(dateStr) < new Date();
  const variant = chipVariant(insp.status, isOverdue);

  return (
    <Link href={`/inspections/${insp.id}`} className={`calendar-chip ${variant}`}>
      <span>{isOverdue ? <AlertTriangle size={11} /> : statusIcon(insp.status)}</span>
      <div style={{ minWidth: 0 }}>
        <p className="calendar-chip__title">
          {day ? `${day} — ` : ""}{insp.title}
        </p>
        <div className="calendar-chip__meta">
          {insp.autoGenerated && (
            <span className="calendar-chip__ai-badge">
              <Sparkles size={9} /> AI
            </span>
          )}
          {insp.assigneeName && (
            <span className="calendar-chip__assignee">
              <User size={9} /> {insp.assigneeName}
            </span>
          )}
        </div>
      </div>
    </Link>
  );
}

function MonthBlock({ monthKey, inspections }: { monthKey: string; inspections: Inspection[] }) {
  const [year, monthStr] = monthKey.split("-");
  const monthIndex = parseInt(monthStr, 10) - 1;
  const monthName = MONTH_NAMES[monthIndex];
  const now = new Date();
  const yearNum = parseInt(year, 10);
  const isCurrentMonth = now.getFullYear() === yearNum && now.getMonth() === monthIndex;
  const isPast = new Date(yearNum, monthIndex + 1, 1) < now && !isCurrentMonth;

  const overdueCount = inspections.filter(
    (i) => i.status === "planned" && i.scheduledFor && new Date(i.scheduledFor) < now
  ).length;

  const blockClass = [
    "calendar-month-block",
    isCurrentMonth ? "calendar-month-block--current" : "",
    isPast && !isCurrentMonth ? "calendar-month-block--past" : "",
  ].filter(Boolean).join(" ");

  return (
    <div className={blockClass}>
      <div className="calendar-month-header">
        <div>
          <p className="calendar-month-header__label">{year}</p>
          <h3 className="calendar-month-header__name">
            {monthName}
            {isCurrentMonth && <span className="calendar-current-badge">Current</span>}
          </h3>
        </div>
        <div className="calendar-month-count-col">
          <span className="calendar-month-count">{inspections.length}</span>
          {overdueCount > 0 && (
            <span className="calendar-month-overdue">{overdueCount} overdue</span>
          )}
        </div>
      </div>

      {inspections.length === 0 ? (
        <p className="calendar-empty">No inspections scheduled</p>
      ) : (
        <div>
          {inspections.map((insp) => (
            <InspectionChip key={insp.id} insp={insp} />
          ))}
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

const LEGEND_ITEMS: { label: string; bg: string; border: string }[] = [
  { label: "Planned",     bg: "#eff6ff", border: "#bfdbfe" },
  { label: "In progress", bg: "#fefce8", border: "#fde68a" },
  { label: "Completed",   bg: "#f0fdf4", border: "#bbf7d0" },
  { label: "Cancelled",   bg: "#f9fafb", border: "#e5e7eb" },
  { label: "Overdue",     bg: "#fef2f2", border: "#fca5a5" },
];

export default async function InspectionCalendarPage() {
  const inspections = await listInspections().catch(() => []);

  const grouped = groupByMonth(inspections);
  const monthRange = buildMonthRange();

  const totalScheduled = inspections.filter((i) => ["planned", "in_progress"].includes(i.status)).length;
  const totalOverdue = inspections.filter(
    (i) => i.status === "planned" && i.scheduledFor && new Date(i.scheduledFor) < new Date()
  ).length;
  const autoGenCount = inspections.filter((i) => i.autoGenerated).length;

  return (
    <AppShell>
      <div className="page-stack">
        <header className="page-header">
          <div className="page-header-left">
            <p className="section-label">
              Operate · <Link href="/inspections">Inspection Register</Link> / Calendar
            </p>
            <h1>Compliance Calendar</h1>
            <p className="muted">
              All scheduled inspections across your 12-month compliance window.
              AI-generated assignments are marked with a purple badge.
            </p>
          </div>
          <Link className="button-secondary" href="/inspections">← All Inspections</Link>
        </header>

        <section className="kpi-grid" aria-label="Calendar summary">
          <div className="kpi-card kpi-card--blue">
            <div className="kpi-label">Scheduled</div>
            <div className="kpi-value">{totalScheduled}</div>
            <div className="kpi-sub">Planned or in progress</div>
          </div>
          <div className={`kpi-card ${totalOverdue > 0 ? "kpi-card--red" : "kpi-card--green"}`}>
            <div className="kpi-label">Overdue</div>
            <div className="kpi-value">{totalOverdue}</div>
            <div className="kpi-sub">{totalOverdue > 0 ? "Past due date" : "All on track"}</div>
          </div>
          <div className="kpi-card kpi-card--purple">
            <div className="kpi-label">AI-Assigned</div>
            <div className="kpi-value">{autoGenCount}</div>
            <div className="kpi-sub">Auto-scheduled by engine</div>
          </div>
          <div className="kpi-card kpi-card--green">
            <div className="kpi-label">Completed</div>
            <div className="kpi-value">{inspections.filter((i) => i.status === "completed").length}</div>
            <div className="kpi-sub">Inspections closed</div>
          </div>
        </section>

        <div className="calendar-legend" aria-label="Status legend">
          {LEGEND_ITEMS.map(({ label, bg, border }) => (
            <div key={label} className="calendar-legend__item">
              <span className="calendar-legend__dot" style={{ background: bg, border: `1px solid ${border}` }} />
              {label}
            </div>
          ))}
          <div className="calendar-legend__item">
            <span className="calendar-chip__ai-badge"><Sparkles size={9} /> AI</span>
            AI-generated
          </div>
        </div>

        <div className="form-action-row">
          <Link href="/inspections" className="button-secondary compact">
            <Sparkles size={13} /> View Required Inspections
          </Link>
        </div>

        <div className="calendar-month-grid" aria-label="Compliance calendar by month">
          {monthRange.map((key) => (
            <MonthBlock
              key={key}
              monthKey={key}
              inspections={grouped.get(key) ?? []}
            />
          ))}
        </div>
      </div>
    </AppShell>
  );
}
