export const dynamic = "force-dynamic";

import Link from "next/link";
import { Calendar, ChevronLeft, Sparkles, AlertTriangle, Clock, CheckCircle2, User } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { listInspections, inspectionTypeLabels, type Inspection, type InspectionStatus } from "@/lib/supabase/inspection-service";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];

const STATUS_COLORS: Record<InspectionStatus, { bg: string; text: string; border: string }> = {
  planned:     { bg: "#eff6ff", text: "#1d4ed8", border: "#bfdbfe" },
  in_progress: { bg: "#fefce8", text: "#92400e", border: "#fde68a" },
  completed:   { bg: "#f0fdf4", text: "#166534", border: "#bbf7d0" },
  cancelled:   { bg: "#f9fafb", text: "#6b7280", border: "#e5e7eb" },
};

function statusIcon(status: InspectionStatus) {
  if (status === "planned")     return <Clock size={11} />;
  if (status === "in_progress") return <AlertTriangle size={11} />;
  if (status === "completed")   return <CheckCircle2 size={11} />;
  return null;
}

function groupByMonth(inspections: Inspection[]): Map<string, Inspection[]> {
  const map = new Map<string, Inspection[]>();
  for (const insp of inspections) {
    const dateStr = insp.nextDueDate ?? insp.scheduledFor ?? insp.createdAt;
    if (!dateStr) continue;
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) continue;
    const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
    if (!map.has(key)) map.set(key, []);
    map.get(key)!.push(insp);
  }
  // Sort within each month by date
  for (const [, items] of map) {
    items.sort((a, b) => {
      const da = new Date(a.nextDueDate ?? a.scheduledFor ?? "");
      const db = new Date(b.nextDueDate ?? b.scheduledFor ?? "");
      return da.getTime() - db.getTime();
    });
  }
  return map;
}

function buildMonthRange(): string[] {
  const now = new Date();
  const keys: string[] = [];
  for (let i = -1; i <= 11; i++) {
    const d = new Date(now.getFullYear(), now.getMonth() + i, 1);
    keys.push(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`);
  }
  return keys;
}

// ---------------------------------------------------------------------------
// Components
// ---------------------------------------------------------------------------

function InspectionChip({ insp }: { insp: Inspection }) {
  const colors = STATUS_COLORS[insp.status];
  const dateStr = insp.nextDueDate ?? insp.scheduledFor;
  const day = dateStr ? new Date(dateStr).getDate() : null;
  const isOverdue = insp.status === "planned" && dateStr && new Date(dateStr) < new Date();

  return (
    <Link
      href={`/inspections/${insp.id}`}
      style={{
        display: "flex",
        alignItems: "flex-start",
        gap: "8px",
        padding: "8px 10px",
        borderRadius: "6px",
        border: `1px solid ${isOverdue ? "#fca5a5" : colors.border}`,
        background: isOverdue ? "#fef2f2" : colors.bg,
        textDecoration: "none",
        marginBottom: "6px",
        transition: "box-shadow 0.15s",
      }}
    >
      <span style={{ color: isOverdue ? "#b91c1c" : colors.text, marginTop: "2px", flexShrink: 0 }}>
        {isOverdue ? <AlertTriangle size={11} /> : statusIcon(insp.status)}
      </span>
      <div style={{ minWidth: 0 }}>
        <p style={{
          margin: 0,
          fontSize: "12px",
          fontWeight: 600,
          color: isOverdue ? "#b91c1c" : colors.text,
          whiteSpace: "nowrap",
          overflow: "hidden",
          textOverflow: "ellipsis",
          maxWidth: "200px",
        }}>
          {day ? `${day} — ` : ""}{insp.title}
        </p>
        <div style={{ display: "flex", alignItems: "center", gap: "6px", marginTop: "2px", flexWrap: "wrap" }}>
          {insp.autoGenerated && (
            <span style={{ fontSize: "10px", color: "#7c3aed", background: "#f5f3ff", borderRadius: "4px", padding: "1px 5px", border: "1px solid #ddd6fe", display: "inline-flex", alignItems: "center", gap: "3px" }}>
              <Sparkles size={9} /> AI
            </span>
          )}
          {insp.assigneeName && (
            <span style={{ fontSize: "10px", color: "#6b7280", display: "inline-flex", alignItems: "center", gap: "3px" }}>
              <User size={9} /> {insp.assigneeName}
            </span>
          )}
        </div>
      </div>
    </Link>
  );
}

function MonthBlock({ monthKey, inspections }: { monthKey: string; inspections: Inspection[] }) {
  const [year, monthStr] = monthKey.split("-");
  const monthIndex = parseInt(monthStr, 10) - 1;
  const monthName = MONTH_NAMES[monthIndex];
  const now = new Date();
  const isCurrentMonth =
    now.getFullYear() === parseInt(year, 10) && now.getMonth() === monthIndex;
  const isPast =
    new Date(parseInt(year, 10), monthIndex + 1, 1) < now &&
    !isCurrentMonth;

  const overdueCount = inspections.filter(
    (i) => i.status === "planned" && i.scheduledFor && new Date(i.scheduledFor) < now
  ).length;

  return (
    <div
      style={{
        border: isCurrentMonth ? "2px solid #1e3a5f" : "1px solid #e5e7eb",
        borderRadius: "10px",
        padding: "16px",
        background: isCurrentMonth ? "#f0f5ff" : isPast ? "#fafafa" : "#fff",
        minWidth: "260px",
        flex: "1 1 260px",
        maxWidth: "320px",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "12px" }}>
        <div>
          <p style={{ margin: 0, fontSize: "11px", fontWeight: 600, color: "#6b7280", textTransform: "uppercase", letterSpacing: "0.05em" }}>
            {year}
          </p>
          <h3 style={{ margin: 0, fontSize: "16px", fontWeight: 700, color: isCurrentMonth ? "#1e3a5f" : "#111827" }}>
            {monthName}
            {isCurrentMonth && (
              <span style={{ marginLeft: "8px", fontSize: "11px", fontWeight: 500, color: "#1d4ed8", background: "#dbeafe", borderRadius: "4px", padding: "2px 6px" }}>
                Current
              </span>
            )}
          </h3>
        </div>
        <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: "2px" }}>
          <span style={{ fontSize: "20px", fontWeight: 700, color: "#111827" }}>{inspections.length}</span>
          {overdueCount > 0 && (
            <span style={{ fontSize: "10px", color: "#b91c1c", fontWeight: 600 }}>
              {overdueCount} overdue
            </span>
          )}
        </div>
      </div>

      {inspections.length === 0 ? (
        <p style={{ fontSize: "12px", color: "#9ca3af", margin: 0, fontStyle: "italic" }}>No inspections scheduled</p>
      ) : (
        <div>
          {inspections.map((insp) => (
            <InspectionChip key={insp.id} insp={insp} />
          ))}
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default async function InspectionCalendarPage() {
  const inspections = await listInspections().catch(() => []);

  const grouped = groupByMonth(inspections);
  const monthRange = buildMonthRange();

  const totalScheduled = inspections.filter((i) => ["planned", "in_progress"].includes(i.status)).length;
  const totalOverdue = inspections.filter(
    (i) => i.status === "planned" && i.scheduledFor && new Date(i.scheduledFor) < new Date()
  ).length;
  const autoGenCount = inspections.filter((i) => i.autoGenerated).length;

  return (
    <AppShell>
      <div className="page-stack">
        <header className="page-header">
          <Link href="/inspections" style={{ display: "inline-flex", alignItems: "center", gap: "6px", fontSize: "13px", color: "#6b7280", textDecoration: "none", marginBottom: "8px" }}>
            <ChevronLeft size={14} /> Back to Inspections
          </Link>
          <p className="section-label" style={{ display: "flex", alignItems: "center", gap: "6px" }}>
            <Sparkles size={13} /> AI Compliance Calendar
          </p>
          <h1>Compliance Calendar</h1>
          <p className="muted">
            All scheduled inspections across your 12-month compliance window. AI-generated assignments are marked with a purple badge.
          </p>
        </header>

        {/* Summary strip */}
        <section className="command-card-grid" aria-label="Calendar summary">
          <article className="command-card platform-blue">
            <div><span><Calendar size={16} /></span><strong>Scheduled</strong></div>
            <small>{totalScheduled}</small>
            <em>Planned or active inspections.</em>
          </article>
          <article className={`command-card ${totalOverdue > 0 ? "platform-red" : "platform-green"}`}>
            <div><span><AlertTriangle size={16} /></span><strong>Overdue</strong></div>
            <small>{totalOverdue}</small>
            <em>{totalOverdue > 0 ? "Past their due date." : "All on track."}</em>
          </article>
          <article className="command-card platform-blue">
            <div>
              <span><Sparkles size={16} /></span>
              <strong>AI-assigned</strong>
            </div>
            <small>{autoGenCount}</small>
            <em>Created automatically by the compliance engine.</em>
          </article>
          <article className="command-card platform-green">
            <div><span><CheckCircle2 size={16} /></span><strong>Completed</strong></div>
            <small>{inspections.filter((i) => i.status === "completed").length}</small>
            <em>Inspections closed this period.</em>
          </article>
        </section>

        {/* Legend */}
        <div style={{ display: "flex", alignItems: "center", gap: "16px", flexWrap: "wrap", padding: "12px 0" }}>
          {Object.entries(STATUS_COLORS).map(([status, colors]) => (
            <div key={status} style={{ display: "flex", alignItems: "center", gap: "6px", fontSize: "12px" }}>
              <span style={{ width: "10px", height: "10px", borderRadius: "2px", background: colors.bg, border: `1px solid ${colors.border}`, display: "inline-block" }} />
              <span style={{ color: "#374151" }}>{status.replace("_", " ")}</span>
            </div>
          ))}
          <div style={{ display: "flex", alignItems: "center", gap: "6px", fontSize: "12px" }}>
            <span style={{ fontSize: "10px", color: "#7c3aed", background: "#f5f3ff", borderRadius: "4px", padding: "1px 5px", border: "1px solid #ddd6fe" }}>
              <Sparkles size={9} style={{ display: "inline" }} /> AI
            </span>
            <span style={{ color: "#374151" }}>AI-generated</span>
          </div>
        </div>

        {/* Refresh button for admins */}
        <div style={{ display: "flex", justifyContent: "flex-end" }}>
          <Link
            href="/inspections"
            className="button-secondary compact"
            style={{ display: "inline-flex", alignItems: "center", gap: "6px" }}
          >
            <Sparkles size={13} /> View Required Inspections
          </Link>
        </div>

        {/* Calendar grid */}
        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: "16px",
          }}
          aria-label="Compliance calendar by month"
        >
          {monthRange.map((key) => (
            <MonthBlock
              key={key}
              monthKey={key}
              inspections={grouped.get(key) ?? []}
            />
          ))}
        </div>
      </div>
    </AppShell>
  );
}
