import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const foundationPage = readFileSync(join(process.cwd(), "src/app/foundation/page.tsx"), "utf8");
const foundationClient = readFileSync(join(process.cwd(), "src/app/foundation/FoundationWorkflowClient.tsx"), "utf8");
const foundationActions = readFileSync(join(process.cwd(), "src/app/foundation/actions.ts"), "utf8");
const foundationData = readFileSync(join(process.cwd(), "src/lib/supabase/data.ts"), "utf8");
const foundationActionInputs = readFileSync(join(process.cwd(), "src/lib/foundation/action-inputs.ts"), "utf8");
const foundationReviewActions = readFileSync(join(process.cwd(), "src/lib/foundation/review-actions.ts"), "utf8");
const foundationWriteService = readFileSync(join(process.cwd(), "src/lib/supabase/foundation-write-service.ts"), "utf8");
const companyProfilePage = readFileSync(join(process.cwd(), "src/app/company-profile/page.tsx"), "utf8");
const operationsPage = readFileSync(join(process.cwd(), "src/app/operations/page.tsx"), "utf8");
const workbenchPage = readFileSync(join(process.cwd(), "src/app/workbench/page.tsx"), "utf8");
const myWorkPage = readFileSync(join(process.cwd(), "src/app/my-work/page.tsx"), "utf8");
const workbenchClient = readFileSync(join(process.cwd(), "src/components/WorkbenchClient.tsx"), "utf8");
const workKpis = readFileSync(join(process.cwd(), "src/lib/foundation/work-kpis.ts"), "utf8");
const auditPage = readFileSync(join(process.cwd(), "src/app/admin/audit/page.tsx"), "utf8");
const appShell = readFileSync(join(process.cwd(), "src/components/AppShell.tsx"), "utf8");
const reviewActionsPanel = readFileSync(join(process.cwd(), "src/components/FoundationReviewActionsPanel.tsx"), "utf8");
const notificationCenter = readFileSync(join(process.cwd(), "src/components/FoundationNotificationCenter.tsx"), "utf8");
const copyVerificationButton = readFileSync(join(process.cwd(), "src/components/CopyVerificationSummaryButton.tsx"), "utf8");
const notesMigration = readFileSync(join(process.cwd(), "supabase/migrations/20260529143000_audit_readiness_notes.sql"), "utf8");

describe("foundation UI alignment", () => {
  it("surfaces BioType, core component, AI workflow, and human validation sections", () => {
    expect(foundationPage).toContain("Common Utilities");
    expect(foundationPage).toContain("BioType Branching Engine");
    expect(foundationPage).toContain("AI Guardrails");
    expect(foundationPage).toContain("Human Validation Workflow");
  });

  it("shows BioType selections on the company profile surface", () => {
    expect(companyProfilePage).toContain("BioType Branching Engine");
    expect(companyProfilePage).toContain("Selected operating profile");
  });

  it("adds Foundation edit workflows without restoring one-click demo seeding", () => {
    expect(foundationPage).toContain("FoundationWorkflowClient");
    expect(foundationPage).toContain("getFoundationAdminAccessSummary");
    expect(foundationPage).toContain("canManage={adminAccess.isOwner}");
    expect(foundationClient).toContain("updateFoundationBioTypeSelectionAction");
    expect(foundationClient).toContain("updateFoundationIntakeResponseAction");
    expect(foundationClient).toContain("updateFoundationEvidenceReadinessAction");
    expect(foundationClient).toContain("Create starter Foundation rows");
    expect(foundationActions).toContain("createFoundationStarterRecordsAction");
    expect(foundationData).toContain("createFoundationStarterRecords");
    expect(foundationData).toContain("foundation_starter_records_created");
    expect(foundationClient).toContain("System Reliance edit workflows are locked");
    expect(foundationClient).toContain("Generate Action Plan");
    expect(foundationClient).toContain("SEED DEMO DATA");
    expect(foundationClient).toContain("Current foundation counts");
    expect(foundationActions).toContain("seedNorthStarWithConfirmationAction");
    expect(foundationActions).not.toContain("seedIntelligenceFoundationAction");
    expect(foundationData).toContain("hasOpenFoundationRecommendation");
    expect(foundationData).toContain("actionType: \"foundation_review_action\"");
    expect(foundationData).toContain("./foundation-write-service");
    expect(foundationWriteService).toContain("Only organization owners can update Foundation");
    expect(foundationData).toContain("Only organization owners can generate Foundation review actions");
  });

  it("surfaces source-traced review actions and audit readiness console", () => {
    expect(foundationData).toContain("getFoundationReviewActionsSummary");
    expect(foundationData).toContain("getFoundationVerificationStatusSummary");
    expect(foundationData).toContain("getFoundationOperationsDashboardSummary");
    expect(foundationData).toContain("getAuditReadinessConsoleSummary");
    expect(foundationData).toContain("foundationActionKey");
    expect(foundationData).toContain("foundationReviewSourceModules");
    expect(foundationPage).toContain("audit-readiness-console");
    expect(foundationPage).toContain("Generated review actions");
    expect(foundationPage).toContain("Owner verification status");
    expect(foundationPage).toContain("Run verification mode");
    expect(foundationPage).toContain("Generated Actions");
    expect(foundationPage).toContain("/my-work");
    expect(foundationPage).toContain("Source Intelligence");
    expect(foundationPage).toContain("Generated Actions");
    expect(foundationPage).toContain("Audit Readiness");
    expect(foundationPage).toContain("Source Drilldowns");
    expect(foundationPage).toContain("command-center-link-strip");
    expect(foundationPage).toContain("command-center-lane");
    expect(foundationPage).toContain("primaryActionHref=\"/my-work\"");
    expect(foundationPage).toContain("Duplicate prevention visibility");
    expect(foundationPage).toContain("verificationStatus.checklist");
    expect(foundationPage).toContain("Verification export summary");
    expect(foundationPage).toContain("Production readiness gate");
    expect(foundationPage).toContain("Verification passed");
    expect(foundationPage).toContain("Final preview signoff note");
    expect(foundationPage).toContain("CopyVerificationSummaryButton");
    expect(copyVerificationButton).toContain("navigator.clipboard.writeText");
    expect(foundationPage).toContain("sourceRecordAnchor");
    expect(operationsPage).toContain("getFoundationReviewActionsSummary");
    expect(operationsPage).toContain("getFoundationOperationsDashboardSummary");
    expect(operationsPage).toContain("Foundation operations dashboard");
    expect(operationsPage).toContain("Blocked task quick actions");
    expect(workbenchPage).toContain("getFoundationReviewActionsSummary");
    expect(auditPage).toContain("getFoundationReviewActionsSummary");
    expect(auditPage).toContain("Audit filters");
    expect(auditPage).toContain("listAuditEvents({ eventType, sourceModule })");
  });

  it("adds owner-only task status controls and source drilldowns", () => {
    expect(foundationData).toContain("updateFoundationReviewTaskStatus");
    expect(foundationData).toContain("updateFoundationReviewTasksStatus");
    expect(foundationData).toContain("getFoundationSourceDrilldownSummary");
    expect(foundationData).toContain("foundation_review_task_status_updated");
    expect(foundationData).toContain("Only generated Foundation review tasks can be updated");
    expect(foundationActions).toContain("updateFoundationReviewTaskStatusAction");
    expect(foundationActions).toContain("createFoundationReviewActionFromSourceAction");
    expect(foundationActions).toContain("addFoundationFinalPreviewSignoffAction");
    expect(foundationData).toContain("createFoundationReviewActionFromSource");
    expect(foundationData).toContain("final_preview_signoff");
    expect(foundationData).toContain("productionPromotionAllowed");
    expect(foundationData).toContain("assigned_to");
    expect(foundationData).toContain("due_date");
    expect(reviewActionsPanel).toContain("updateFoundationReviewTaskStatusAction");
    expect(reviewActionsPanel).toContain("canManage && action.canUpdate && action.taskId");
    expect(reviewActionsPanel).toContain("action-filter-bar");
    expect(reviewActionsPanel).toContain("Action detail and source trace");
    expect(reviewActionsPanel).toContain("returnTo");
    expect(reviewActionsPanel).toContain("Open source section");
    expect(reviewActionsPanel).toContain("Activity history");
    expect(foundationData).toContain("@/lib/foundation/review-actions");
    expect(foundationReviewActions).toContain("getFoundationExactSourceHref");
    expect(foundationReviewActions).toContain("getFoundationTaskStatusHistory");
    expect(foundationReviewActions).toContain("getFoundationActionNextStep");
    expect(foundationData).toContain("getFoundationSourceResolutionStates");
    expect(foundationData).toContain("addFoundationReviewTaskNote");
    expect(foundationData).toContain("addFoundationReviewTasksNote");
    expect(foundationData).toContain("getFoundationProductionVerificationSummary");
    expect(foundationData).toContain("getFoundationNotificationSummary");
    expect(foundationData).toContain("refreshFoundationSourceResolution");
    expect(foundationReviewActions).toContain("createFoundationTaskNotification");
    expect(foundationReviewActions).toContain("createFoundationTaskNotificationIfMissing");
    expect(foundationReviewActions).toContain("createFoundationDueNotifications");
    expect(foundationReviewActions).toContain("getFoundationNotificationLabel");
    expect(foundationData).toContain("updateFoundationNotificationReadState");
    expect(foundationData).toContain("markAllFoundationNotificationsRead");
    expect(foundationReviewActions).toContain("foundation_task_assigned");
    expect(foundationReviewActions).toContain("foundation_task_blocked");
    expect(foundationReviewActions).toContain("foundation_task_due_soon");
    expect(foundationReviewActions).toContain("foundation_task_overdue");
    expect(foundationReviewActions).toContain("foundation_task_ready_for_closure");
    expect(foundationData).toContain("readyForClosureReview");
    expect(foundationData).toContain("Foundation task ready for closure review");
    expect(foundationData).toContain("Members can update only Foundation review tasks assigned to them");
    expect(foundationData).toContain("Members can bulk update only Foundation review tasks assigned to them.");
    expect(foundationData).toContain("Members can bulk note only Foundation review tasks assigned to them.");
    expect(foundationData).toContain("Members can update task status and notes only; priority, assignment, and due dates are owner-only.");
    expect(foundationData).toContain("@/lib/foundation/action-inputs");
    expect(foundationActionInputs).toContain("normalizeFoundationTaskPriority");
    expect(foundationData).toContain("previousPriority");
    expect(foundationData).toContain("actorRole");
    expect(foundationData).toContain("previousStatus");
    expect(foundationData).toContain("previousDueDate");
    expect(foundationData).toContain("previousAssignedTo");
    expect(foundationData).toContain("resolutionState");
    expect(foundationReviewActions).toContain("getProfileDisplayName");
    expect(foundationData).toContain("operatingState");
    expect(foundationData).toContain("sourceResolutionState");
    expect(foundationData).toContain("canUpdate");
    expect(foundationData).toContain("activityHistory");
    expect(reviewActionsPanel).toContain("assignedTo");
    expect(reviewActionsPanel).toContain("dueDate");
    expect(reviewActionsPanel).toContain("canEditAssignment");
    expect(reviewActionsPanel).toContain("canEditDueDate");
    expect(reviewActionsPanel).toContain("canEditPriority");
    expect(reviewActionsPanel).toContain("<select name=\"priority\" defaultValue={action.priority}>");
    expect(reviewActionsPanel).toContain("updateFoundationReviewTasksStatusAction");
    expect(reviewActionsPanel).toContain("addFoundationReviewTasksNoteAction");
    expect(reviewActionsPanel).toContain("Bulk status update");
    expect(reviewActionsPanel).toContain("Bulk activity note");
    expect(reviewActionsPanel).toContain("Add note to selected");
    expect(reviewActionsPanel).toContain("Bulk closeout");
    expect(reviewActionsPanel).toContain("Complete selected");
    expect(reviewActionsPanel).toContain("name=\"status\" type=\"hidden\" value=\"complete\"");
    expect(reviewActionsPanel).toContain("Required to complete selected tasks.");
    expect(reviewActionsPanel).toContain("selectedVisibleTaskIds");
    expect(reviewActionsPanel).toContain("taskIds");
    expect(reviewActionsPanel).toContain("Select ${action.title}");
    expect(reviewActionsPanel).not.toContain("name=\"assignedTo\" value={selectedVisibleTaskIds");
    expect(reviewActionsPanel).not.toContain("name=\"priority\" value={selectedVisibleTaskIds");
    expect(reviewActionsPanel).toContain("initialSavedView");
    expect(reviewActionsPanel).toContain("laneLabel");
    expect(reviewActionsPanel).toContain("laneDescription");
    expect(reviewActionsPanel).toContain("primaryActionHref");
    expect(reviewActionsPanel).toContain("primaryActionLabel");
    expect(reviewActionsPanel).toContain("command-center-lane");
    expect(reviewActionsPanel).toContain("task-command-lane");
    expect(reviewActionsPanel).toContain("closeoutNote");
    expect(reviewActionsPanel).toContain("addFoundationReviewTaskNoteAction");
    expect(reviewActionsPanel).toContain("refreshFoundationSourceResolutionAction");
    expect(reviewActionsPanel).toContain("Source resolution");
    expect(reviewActionsPanel).toContain("Activity history");
    expect(reviewActionsPanel).toContain("task-aging-badge");
    expect(reviewActionsPanel).toContain("task-status-chip");
    expect(reviewActionsPanel).toContain("task-card-meta");
    expect(reviewActionsPanel).toContain("Ready for closure review");
    expect(reviewActionsPanel).toContain("compact-timeline");
    expect(reviewActionsPanel).toContain("Search tasks");
    expect(reviewActionsPanel).toContain("Saved task views");
    expect(reviewActionsPanel).toContain("My open work");
    expect(reviewActionsPanel).toContain("Due soon");
    expect(reviewActionsPanel).toContain("Overdue");
    expect(reviewActionsPanel).toContain("High priority");
    expect(reviewActionsPanel).toContain("<option value=\"urgent\">Urgent</option>");
    expect(reviewActionsPanel).toContain("task-role-chip");
    expect(reviewActionsPanel).toContain("Owner controls");
    expect(reviewActionsPanel).toContain("Assigned member");
    expect(reviewActionsPanel).toContain("TaskEmptyState");
    expect(reviewActionsPanel).toContain("task-lane-empty-state");
    expect(reviewActionsPanel).toContain("TaskDetailDrawer");
    expect(reviewActionsPanel).toContain("Open task detail");
    expect(reviewActionsPanel).toContain("CloseoutNoteCallout");
    expect(reviewActionsPanel).toContain("task-closeout-note");
    expect(reviewActionsPanel).toContain("action.status !== \"complete\"");
    expect(reviewActionsPanel).toContain("Closeout note: ${event.closeoutNote}");
    expect(reviewActionsPanel).toContain("TaskActivityTimeline");
    expect(reviewActionsPanel).toContain("TaskContextBlock");
    expect(reviewActionsPanel).toContain("getSourceResolutionDisplay");
    expect(reviewActionsPanel).toContain("Source resolution");
    expect(reviewActionsPanel).toContain("source-resolution-chip");
    expect(reviewActionsPanel).toContain("Resolved");
    expect(reviewActionsPanel).toContain("Needs review");
    expect(reviewActionsPanel).toContain("Manual review");
    expect(reviewActionsPanel).toContain("No exact source");
    expect(reviewActionsPanel).toContain("getActivityTitle");
    expect(reviewActionsPanel).toContain("Closed with closeout note");
    expect(reviewActionsPanel).toContain("Assignment changed");
    expect(reviewActionsPanel).toContain("Due date changed");
    expect(reviewActionsPanel).toContain("Priority changed");
    expect(reviewActionsPanel).toContain("Source refreshed");
    expect(reviewActionsPanel).toContain("activity-event-meta");
    expect(reviewActionsPanel).toContain("actorRole");
    expect(foundationActions).toContain("normalizeFoundationReturnTo");
    expect(foundationActions).toContain("if (formData.has(\"priority\"))");
    expect(foundationActions).toContain("updateFoundationReviewTasksStatusAction");
    expect(foundationActions).toContain("addFoundationReviewTasksNoteAction");
    expect(foundationActions).toContain("formData.getAll(\"taskIds\")");
    expect(foundationData).toContain("Add a short closeout note before completing selected Foundation review tasks.");
    expect(foundationActions).toContain("revalidatePath(\"/my-work\")");
    expect(foundationActions).toContain("\"/my-work\"");
    expect(foundationActions).toContain("addFoundationReviewTaskNoteAction");
    expect(foundationActions).toContain("refreshFoundationSourceResolutionAction");
    expect(foundationActions).toContain("updateFoundationNotificationReadStateAction");
    expect(foundationActions).toContain("markAllFoundationNotificationsReadAction");
    expect(operationsPage).toContain("returnTo=\"/operations\"");
    expect(auditPage).toContain("returnTo=\"/admin/audit\"");
    expect(auditPage).toContain("foundation_review_task_note_added");
    expect(auditPage).toContain("foundation_source_resolution_refreshed");
    expect(foundationPage).toContain("returnTo=\"/foundation\"");
    expect(workbenchPage).toContain("getFoundationReviewActionsSummary");
    expect(workbenchPage).toContain("getFoundationProductionVerificationSummary");
    expect(workbenchPage).toContain("getFoundationAssigneeOptions");
    expect(workbenchPage).toContain("getFoundationNotificationSummary");
    expect(workbenchClient).toContain("getWorkbenchTaskAgingClass");
    expect(workbenchClient).toContain("Command Summary");
    expect(workbenchClient).toContain("Operating Work");
    expect(workbenchClient).toContain("Workspace Activity");
    expect(notificationCenter).toContain("Notifications");
    expect(workbenchClient).toContain("BioRisk Engine");
    expect(workbenchClient).toContain("command-center-link-strip");
    expect(workbenchClient).toContain("Foundation task lanes");
    expect(workbenchClient).toContain("Completed this week");
    expect(workbenchClient).toContain("Ready for closure");
    expect(workbenchClient).toContain("High-priority work");
    expect(workbenchClient).toContain("ProductionVerificationEvidenceGrid");
    expect(workbenchClient).toContain("Complete your first workflow steps");
    expect(workbenchClient).toContain("production-evidence-list");
    expect(workbenchClient).toContain("Latest workflow save");
    expect(workbenchClient).toContain("Latest task update");
    expect(workbenchClient).toContain("Latest audit event");
    expect(workbenchClient).toContain("Connected workspace");
    expect(workbenchClient).toContain("Overall status");
    expect(workbenchClient).toContain("Getting started");
    expect(workbenchClient).toContain("production-state-badge");
    expect(workbenchClient).toContain("Activity summary only");
    expect(workbenchClient).toContain("This does not certify compliance, approve documents, close CAPAs, validate systems, or replace human review.");
    expect(workbenchClient).toContain("workSpecialFilter");
    expect(workbenchClient).toContain("assigned-work-console");
    expect(workbenchClient).toContain("Assigned to me");
    expect(workbenchClient).toContain("Reset filters");
    expect(notificationCenter).toContain("Notifications");
    expect(workbenchClient).toContain("FoundationNotificationCenter");
    expect(notificationCenter).toContain("notification.label");
    expect(notificationCenter).toContain("notification-type-label");
    expect(notificationCenter).toContain("Mark all read");
    expect(notificationCenter).toContain("Mark unread");
    expect(notificationCenter).toContain("Mark read");
    expect(workbenchClient).toContain("Workbench-to-Foundation context");
    expect(workbenchClient).toContain("canManageFoundationActions");
    expect(workbenchClient).toContain("canEditAssignment={commandSummary.ownerMode}");
    expect(workbenchClient).toContain("canEditPriority={commandSummary.ownerMode}");
    expect(workbenchClient).toContain("href=\"/my-work\"");
    expect(workbenchClient).toContain("productionVerification");
    expect(workbenchClient).toContain("getAssignedWorkDueBucket");
    expect(workbenchClient).toContain("Open source section");
    expect(workbenchClient).toContain("action.nextStep");
    expect(workbenchClient).toContain("WorkbenchCloseoutNote");
    expect(workbenchClient).toContain("task-closeout-note");
    expect(workbenchClient).toContain("action.status !== \"complete\"");
    expect(appShell).toContain("My Work");
    expect(appShell).toContain("/my-work");
    expect(myWorkPage).toContain("export default async function MyWorkPage");
    expect(myWorkPage).toContain("Assigned Work");
    expect(myWorkPage).toContain("Priority/Blocked/Overdue");
    expect(myWorkPage).toContain("Ready for closure");
    expect(notificationCenter).toContain("Notifications");
    expect(myWorkPage).toContain("command-center-link-strip");
    expect(myWorkPage).toContain("command-center-lane");
    expect(myWorkPage).toContain("getFoundationReviewActionsSummary");
    expect(myWorkPage).toContain("getFoundationAssigneeOptions");
    expect(myWorkPage).toContain("getFoundationNotificationSummary");
    expect(notificationCenter).toContain("notifications.unreadCount");
    expect(myWorkPage).toContain("getFoundationWorkKpis");
    expect(myWorkPage).toContain("searchParams");
    expect(myWorkPage).toContain("/my-work?view=overdue#my-work-actions");
    expect(myWorkPage).toContain("/my-work?view=high_priority#my-work-actions");
    expect(myWorkPage).toContain("requestedView ?? (adminAccess.isOwner ? \"all\" : \"my_open\")");
    expect(myWorkPage).toContain("Ready for closure");
    expect(myWorkPage).toContain("High-priority work");
    expect(reviewActionsPanel).toContain("savedTaskViews");
    expect(reviewActionsPanel).toContain("Active saved view");
    expect(reviewActionsPanel).toContain("saved-view-state");
    expect(reviewActionsPanel).toContain("getSavedViewLabel");
    expect(reviewActionsPanel).toContain("taskSortOptions");
    expect(reviewActionsPanel).toContain("Sort");
    expect(reviewActionsPanel).toContain("getSortedActions");
    expect(reviewActionsPanel).toContain("comparePriority");
    expect(reviewActionsPanel).toContain("compareDueDates");
    expect(reviewActionsPanel).toContain("source_module");
    expect(reviewActionsPanel).toContain("sorted by {getSortLabel(sortKey).toLowerCase()}");
    expect(myWorkPage).toContain("FoundationNotificationCenter");
    expect(myWorkPage).toContain("adminAccess.isOwner ? allActions");
    expect(myWorkPage).toContain("canEditAssignment={adminAccess.isOwner}");
    expect(myWorkPage).toContain("canEditDueDate={adminAccess.isOwner}");
    expect(myWorkPage).toContain("canEditPriority={adminAccess.isOwner}");
    expect(foundationPage).toContain("Source Drilldowns");
    expect(foundationPage).toContain("source-drilldown-grid");
    expect(foundationPage).toContain("getFoundationSourceDrilldownSummary");
    expect(foundationPage).toContain("Recommended action");
    expect(foundationPage).toContain("createFoundationReviewActionFromSourceAction");
    expect(workKpis).toContain("getFoundationWorkKpis");
    expect(workKpis).toContain("isFoundationReadyForClosure");
    expect(workKpis).toContain("completedThisWeek");
    expect(workKpis).toContain("highPriority");
    expect(workKpis).toContain("unreadNotifications");
  });

  it("adds audit readiness notes with org scope, RLS, grants, and no user metadata authorization", () => {
    expect(notesMigration).toContain("create table public.audit_readiness_notes");
    expect(notesMigration).toContain("organization_id uuid not null");
    expect(notesMigration).toContain("grant select, insert, update, delete on public.audit_readiness_notes to authenticated");
    expect(notesMigration).toContain("alter table public.audit_readiness_notes enable row level security");
    expect(notesMigration).toContain("profiles.id = (select auth.uid())");
    expect(notesMigration).not.toMatch(/user_metadata/i);
  });
});
